"use strict";
exports.__esModule = true;
exports.Property = exports.DecompositionType = exports.ConceptType = exports.UnitOfMeassure = exports.Currency = exports.InformationType = exports.CharacterSet = exports.FormatVersion = void 0;
var FormatVersion;
(function (FormatVersion) {
    FormatVersion["v101"] = "FIE-1.01";
    FormatVersion["v1995"] = "FIEBDC-3/95";
    FormatVersion["v1998"] = "FIEBDC-3/98";
    FormatVersion["v2002"] = "FIEBDC-3/2002";
    FormatVersion["v2004"] = "FIEBDC-3/2004";
    FormatVersion["v2007"] = "FIEBDC-3/2007";
    FormatVersion["v2012"] = "FIEBDC-3/2012";
    FormatVersion["v2016"] = "FIEBDC-3/2016";
    FormatVersion["v2020"] = "FIEBDC-3/2020";
})(FormatVersion = exports.FormatVersion || (exports.FormatVersion = {}));
var CharacterSet;
(function (CharacterSet) {
    CharacterSet["ANSI"] = "ANSI";
})(CharacterSet = exports.CharacterSet || (exports.CharacterSet = {}));
var InformationType;
(function (InformationType) {
    InformationType[InformationType["Database"] = 1] = "Database";
    InformationType[InformationType["Budget"] = 2] = "Budget";
    InformationType[InformationType["Actual cost"] = 3] = "Actual cost";
    InformationType[InformationType["Database update"] = 4] = "Database update";
})(InformationType = exports.InformationType || (exports.InformationType = {}));
var Currency;
(function (Currency) {
    Currency[Currency["ATS"] = 0] = "ATS";
    Currency[Currency["BEF"] = 1] = "BEF";
    Currency[Currency["DEM"] = 2] = "DEM";
    Currency[Currency["ESP"] = 3] = "ESP";
    Currency[Currency["FIM"] = 4] = "FIM";
    Currency[Currency["FRF"] = 5] = "FRF";
    Currency[Currency["GRD"] = 6] = "GRD";
    Currency[Currency["IEP"] = 7] = "IEP";
    Currency[Currency["ITL"] = 8] = "ITL";
    Currency[Currency["LUF"] = 9] = "LUF";
    Currency[Currency["NLG"] = 10] = "NLG";
    Currency[Currency["PTE"] = 11] = "PTE";
    Currency[Currency["AUD"] = 12] = "AUD";
    Currency[Currency["BGN"] = 13] = "BGN";
    Currency[Currency["CAD"] = 14] = "CAD";
    Currency[Currency["CHF"] = 15] = "CHF";
    Currency[Currency["CYP"] = 16] = "CYP";
    Currency[Currency["CZK"] = 17] = "CZK";
    Currency[Currency["DKK"] = 18] = "DKK";
    Currency[Currency["EEK"] = 19] = "EEK";
    Currency[Currency["EUR"] = 20] = "EUR";
    Currency[Currency["GBP"] = 21] = "GBP";
    Currency[Currency["HKD"] = 22] = "HKD";
    Currency[Currency["HUF"] = 23] = "HUF";
    Currency[Currency["ISK"] = 24] = "ISK";
    Currency[Currency["JPY"] = 25] = "JPY";
    Currency[Currency["KRW"] = 26] = "KRW";
    Currency[Currency["LTL"] = 27] = "LTL";
    Currency[Currency["LVL"] = 28] = "LVL";
    Currency[Currency["MTL"] = 29] = "MTL";
    Currency[Currency["NOK"] = 30] = "NOK";
    Currency[Currency["NZD"] = 31] = "NZD";
    Currency[Currency["PLN"] = 32] = "PLN";
    Currency[Currency["ROL"] = 33] = "ROL";
    Currency[Currency["SEK"] = 34] = "SEK";
    Currency[Currency["SGD"] = 35] = "SGD";
    Currency[Currency["SIT"] = 36] = "SIT";
    Currency[Currency["SKK"] = 37] = "SKK";
    Currency[Currency["TRL"] = 38] = "TRL";
    Currency[Currency["USD"] = 39] = "USD";
    Currency[Currency["ZAR"] = 40] = "ZAR";
})(Currency = exports.Currency || (exports.Currency = {}));
var UnitOfMeassure;
(function (UnitOfMeassure) {
    UnitOfMeassure[UnitOfMeassure["m"] = 0] = "m";
    UnitOfMeassure[UnitOfMeassure["m2"] = 1] = "m2";
    UnitOfMeassure[UnitOfMeassure["m3"] = 2] = "m3";
    UnitOfMeassure[UnitOfMeassure["kg"] = 3] = "kg";
    UnitOfMeassure[UnitOfMeassure["km"] = 4] = "km";
    UnitOfMeassure[UnitOfMeassure["t"] = 5] = "t";
    UnitOfMeassure[UnitOfMeassure["l"] = 6] = "l";
    UnitOfMeassure[UnitOfMeassure["h"] = 7] = "h";
    UnitOfMeassure[UnitOfMeassure["d"] = 8] = "d";
    UnitOfMeassure[UnitOfMeassure["to"] = 9] = "to";
    UnitOfMeassure[UnitOfMeassure["ha"] = 10] = "ha";
    UnitOfMeassure[UnitOfMeassure["cm3"] = 11] = "cm3";
    UnitOfMeassure[UnitOfMeassure["cm2"] = 12] = "cm2";
    UnitOfMeassure[UnitOfMeassure["dm3"] = 13] = "dm3";
    UnitOfMeassure[UnitOfMeassure["u"] = 14] = "u";
    UnitOfMeassure[UnitOfMeassure["mu"] = 15] = "mu";
    UnitOfMeassure[UnitOfMeassure["cu"] = 16] = "cu";
    UnitOfMeassure[UnitOfMeassure["month"] = 17] = "month";
})(UnitOfMeassure = exports.UnitOfMeassure || (exports.UnitOfMeassure = {}));
var ConceptType;
(function (ConceptType) {
    ConceptType[ConceptType["Unclassified"] = 0] = "Unclassified";
    ConceptType[ConceptType["Labour"] = 1] = "Labour";
    ConceptType[ConceptType["Machinery and auxiliary equipment"] = 2] = "Machinery and auxiliary equipment";
    ConceptType[ConceptType["Materials"] = 3] = "Materials";
    ConceptType[ConceptType["Additional waste components"] = 4] = "Additional waste components";
    ConceptType[ConceptType["Waste classification"] = 5] = "Waste classification";
})(ConceptType = exports.ConceptType || (exports.ConceptType = {}));
var DecompositionType;
(function (DecompositionType) {
    DecompositionType[DecompositionType["Placement-component waste"] = 0] = "Placement-component waste";
    DecompositionType[DecompositionType["Demolition-component waste"] = 1] = "Demolition-component waste";
    DecompositionType[DecompositionType["Excavation-component wastes"] = 2] = "Excavation-component wastes";
    DecompositionType[DecompositionType["Packaging-component wastes"] = 3] = "Packaging-component wastes";
})(DecompositionType = exports.DecompositionType || (exports.DecompositionType = {}));
var Property;
(function (Property) {
    Property["Output"] = "o";
    Property["Waste factor"] = "wf";
})(Property = exports.Property || (exports.Property = {}));
